.PHONY =all say_hello generate clean

# all: say_hello generate

say_hello:
	@echo "Hello world"

generate:
	@echo "creating 5 text files"
	touch file-{1..5}.txt

clean:
	@echo "cleaning text files"
	rm *.txt
